@startuml component
title Registration
header Gilded Rose API ©2021

actor API_User
node Public_Controller
node User_Service
database User_Storage

API_User <-> Public_Controller
Public_Controller <-> User_Service
User_Service <-> User_Storage
@enduml
