@startuml
title Registration
actor Buyer

Buyer -> WebController : /register
WebController -> UserService : save()
UserService->UserService: Store in memory
WebController <-- UserService : return
Buyer <-- WebController : API token
@enduml
