@startuml

autonumber
header Gilded Rose API ©2021
footer Page 1 of 1
hide footbox

skinparam responseMessageBelowArrow true
skinparam sequence {
  ActorBackgroundColor DarkKhaki
  ActorBorderColor Blue
  DatabaseBackgroundColor Gray
  DatabaseBorderColor Black
  LifeLineBorderColor Blue
  ParticipantBackgroundColor WhiteSmoke
  ParticipantBorderColor Black
}
skinparam style strictuml

title Registration (email invalid)

actor API_User
participant PublicWebController

API_User -[#0000FF]>x PublicWebController : POST email address to /register
note right of API_User
 Invalid email e.g. a.b@c.de
end note
activate PublicWebController
PublicWebController <-- PublicWebController : validate email
API_User <[#DarkGreen]-- PublicWebController : return 4xx status code
deactivate PublicWebController

@enduml


