@startuml

autonumber
header Gilded Rose API ©2021
footer Page 1 of 1
hide footbox

skinparam responseMessageBelowArrow true
skinparam sequence {
  ActorBackgroundColor DarkKhaki
  ActorBorderColor Blue
  DatabaseBackgroundColor Gray
  DatabaseBorderColor Black
  LifeLineBorderColor Blue
  ParticipantBackgroundColor WhiteSmoke
  ParticipantBorderColor Black
}
skinparam style strictuml

title Registration (success)

actor API_User
participant PublicWebController
participant UserService
database Users

API_User -[#0000FF]> PublicWebController : POST email address to /register
note right of API_User
 Valid emails, for //demo// purposes:
   - ""customer_x@go.to""
   - ""customer_x@the.wang""
   - ""customer_x@us.online""
   - ""customer_x@cheese.pizza""
end note
activate PublicWebController
PublicWebController <-- PublicWebController : generate UUID
PublicWebController <-- PublicWebController : create User w/UUID
PublicWebController -[#0000FF]> UserService : save(User)
activate UserService
UserService -[#0000FF]> Users : put(UUID, User)
UserService <[#DarkGreen]-- Users : return
PublicWebController <[#DarkGreen]-- UserService : return
deactivate UserService
API_User <[#DarkGreen]-- PublicWebController : return UUID as API token
deactivate PublicWebController

@enduml
