@startuml
title Registration
header Gilded Rose API ©2021

actor API_User

API_User -> WebController : /register
WebController -> UserService : save()
' The following self-reference seems to defy web browser caching?!
UserService -> UserService: Store in memory
WebController <-- UserService : return
API_User <-- WebController : API token
@enduml
